[package]
name = "autotyper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
widestring = "1.0.2"

[dependencies.windows]
version = "0.48.0"
features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_TextServices"
]
